import { chapter, task as q, tutorial as t, page as p } from './content.js';
const h = (concept, step) => [concept, step];
export default chapter({id:'aggregate-ledger',title:'The whole night’s work',place:'The Archive',scene:'archive',topic:'COUNT · SUM · AVG · MIN · MAX',brief:'Summarize a set of orders in one row.',tables:['orders'],
 storyPages:[p('A question for the whole book','PROFESSOR QUILL','The beacon keeper asks how much work remains. Quill closes his jar catalog and opens the orders ledger. “Now we need one answer about many records.”'),p("The unfinished entries","IONA","Iona notices blank delivery dates among the orders. “Those are still orders. We just have no recorded delivery.” She draws separate boxes for the full count and the completed count before you calculate either.")],
 ending:p('A total worth planning around','IONA','Iona reads the totals before setting out the flasks. Unknown delivery dates remain unknown; every order still contributes to the order count.'),
 tutorial:t(['An aggregate summarizes multiple rows. COUNT(*) counts rows; COUNT(column) counts non-NULL values; COUNT(DISTINCT column) counts distinct non-NULL values.', 'SUM adds values. AVG computes their average. MIN and MAX find the smallest and largest. These aggregates ignore NULL inputs.', 'With no GROUP BY, aggregate-only output has one row, even for an empty input: COUNT returns zero, while SUM, AVG, MIN, and MAX return NULL. Do not select an unrelated bare column beside a whole-table aggregate.'], 'SELECT MIN(batches), MAX(batches) FROM orders;', 'One row reports the smallest and largest batch quantities across the ledger.'),
 tasks:[q('Return total order count and the count with a recorded delivered_on value, in that order.','SELECT COUNT(*), COUNT(delivered_on) FROM orders;',h('COUNT(*) includes every row.', 'COUNT(delivered_on) skips unknown dates.')),q('Return SUM(batches) and AVG(batches) for all orders, in that order.','SELECT SUM(batches), AVG(batches) FROM orders;',h('Both calculations summarize the same input set.', 'Select only the two aggregates.')),q('Return the count of distinct destinations, minimum unit_price, and maximum unit_price for undelivered orders, in that order.','SELECT COUNT(DISTINCT destination), MIN(unit_price), MAX(unit_price) FROM orders WHERE delivered_on IS NULL;',h('Filter missing delivery dates before aggregating.', 'DISTINCT belongs inside COUNT for the first value.'))],
 crafts:[['batch-vial','Batch Vial','potion','Measure the completed shipments.',q('Return total batches for delivered orders only.','SELECT SUM(batches) FROM orders WHERE delivered_on IS NOT NULL;',h('Filter recorded delivery dates.', 'SUM adds batch values.'))],['fare-spark','Fare Spark','spell','Calculate the value written on the order book.',q('Return SUM(batches * unit_price) across all orders.','SELECT SUM(batches * unit_price) FROM orders;',h('Calculate each row’s value inside SUM.', 'Multiplication happens before the total.'))],['route-counter','Route Counter','charm','Count how many routes appear in completed deliveries.',q('Return COUNT(DISTINCT destination) for delivered orders.','SELECT COUNT(DISTINCT destination) FROM orders WHERE delivered_on IS NOT NULL;',h('A route is a distinct destination.', 'Restrict the source rows to known delivery dates.'))]],
});
