import { chapter, task as q, tutorial as t, page as p } from './content.js';
const h = (concept, step) => [concept, step];
export default chapter({id:'conditional-labels',title:'Flags for the dispatch crew',place:'The Workshop',scene:'workshop',topic:'CASE · WHEN · ELSE',brief:'Turn conditions into readable categories.',tables:['ingredients'],
 storyPages:[p('A flag beside each crate','IONA','The ferry crew asks for words instead of potency numbers. Iona brings three colors of cloth. “We can translate a reading into a category without losing the ingredient beside it.”'),p("The first flag wins","PROFESSOR QUILL","Quill reaches for the ordinary lamp flag on a powerful glowing crate. Iona taps the brighter beacon flag. “Check the special case first. Otherwise every beacon gets labeled as an ordinary lamp.”")],
 ending:p('Every crate has a flag','IONA','The flags follow the written boundaries. Iona leaves the rules pinned to the manifest so the next crew can interpret them.'),
 tutorial:t(["CASE WHEN condition THEN value ELSE fallback END calculates a value for each row. It does not filter rows.", 'SQLite uses the first WHEN that is true. Put the most restrictive threshold first when ranges overlap.', 'ELSE handles rows for which no WHEN is true. Without ELSE, those rows receive NULL. Text labels need single quotes.'], "SELECT name, CASE WHEN glowing = 1 THEN 'lit' ELSE 'dark' END AS glow_label FROM ingredients;",'Every ingredient stays in the output with a readable glow label.'),
 tasks:[q("Return name and a CASE label: 'strong' for potency at least 7, otherwise 'gentle'.", "SELECT name, CASE WHEN potency >= 7 THEN 'strong' ELSE 'gentle' END FROM ingredients;",h('CASE computes the second column.', 'Use ELSE for everything below seven.'),{requires:'CASE'}),q("Return id and a CASE label: 'high' for potency at least 8, 'middle' for potency at least 5, otherwise 'low'.", "SELECT id, CASE WHEN potency >= 8 THEN 'high' WHEN potency >= 5 THEN 'middle' ELSE 'low' END FROM ingredients;",h('Test the highest band first.', 'The first true branch wins.'),{requires:'CASE'}),q("Return name and a CASE label: 'beacon' when glowing is 1 AND potency is at least 7, 'lamp' for other glowing ingredients, otherwise 'unlit'.", "SELECT name, CASE WHEN glowing = 1 AND potency >= 7 THEN 'beacon' WHEN glowing = 1 THEN 'lamp' ELSE 'unlit' END FROM ingredients;",h('The beacon rule is more restrictive than the lamp rule.', 'Test both properties before the simpler glow test.'),{requires:'CASE'})],
 crafts:[['soft-tag','Soft Tag','charm','Mark gentle training supplies.',q("Return name and CASE label 'training' when potency is below 5, otherwise 'reserve'.","SELECT name, CASE WHEN potency < 5 THEN 'training' ELSE 'reserve' END FROM ingredients;",h('Below excludes five.', 'Keep all rows and calculate a label.'),{requires:'CASE'})],['glow-code','Glow Code','spell','Encode the glow reading on a practice seal.',q('Return id and CASE value 10 when glowing is 1, otherwise 0.','SELECT id, CASE WHEN glowing = 1 THEN 10 ELSE 0 END FROM ingredients;',h('CASE can return numbers.', 'Neither numeric result needs quotes.'),{requires:'CASE'})],['edge-tonic','Edge Tonic','potion','Notice measurements exactly at the boundary.',q("Return name and CASE label 'boundary' when potency equals 7, 'above' when potency exceeds 7, otherwise 'below'.","SELECT name, CASE WHEN potency = 7 THEN 'boundary' WHEN potency > 7 THEN 'above' ELSE 'below' END FROM ingredients;",h('Treat equality as its own branch.', 'Use ELSE for the remaining lower readings.'),{requires:'CASE'})]],
});
