import { chapter, task as q, tutorial as t, page as p } from './content.js';
const h = (concept, step) => [concept, step];
export default chapter({id:'distinct-values',title:'One mark per kind',place:'The Archive',scene:'archive',topic:'DISTINCT · tuples',brief:'Remove duplicate output combinations.',tables:['ingredients'],
 storyPages:[p('Too many stamps','PROFESSOR QUILL','Quill has stamped one form per jar, but the keeper asked which kinds of readings exist. “Rows and kinds are different questions,” he says, setting his stamp down.'),p("Two jars, one label","IONA","Iona finds two jars carrying the same label. “Both belong in the inventory. Only one spelling belongs in the label index.” She opens a second notebook so neither list has to do the other’s work.")],
 ending:p('The smaller index','PROFESSOR QUILL','The summary keeps each requested combination once. It is shorter than a jar-by-jar record because it answers a different question.'),
 tutorial:t(['SELECT DISTINCT removes duplicate returned rows after the selected columns are considered together.', 'DISTINCT name gives one row per name, even if multiple IDs share it. DISTINCT name, potency gives one row per name-and-potency combination.', 'Adding a unique ID makes each selected row distinct again. DISTINCT does not count rows and does not guarantee sorting.'], 'SELECT DISTINCT glowing FROM ingredients;', 'The output lists which glow values occur, rather than repeating one value per ingredient.'),
 tasks:[q('Return each different ingredient name once using DISTINCT.','SELECT DISTINCT name FROM ingredients;',h('Choose only the value whose duplicates should collapse.', 'Put DISTINCT immediately after SELECT.'),{requires:'DISTINCT'}),q('Return each different glowing-and-potency combination once, in that column order.','SELECT DISTINCT glowing, potency FROM ingredients;',h('Distinctness applies to both output columns together.', 'Do not include the unique ID.'),{requires:'DISTINCT'}),q('For glowing ingredients, return each different potency once in ascending order.','SELECT DISTINCT potency FROM ingredients WHERE glowing = 1 ORDER BY potency ASC;',h('Filter the source rows before deduplicating strengths.', 'The requested order needs ORDER BY.'),{requires:'DISTINCT',ordered:true})],
 crafts:[['strength-index','Strength Index','charm','Keep one mark for each available strength.',q('Return each different potency once for all ingredients.','SELECT DISTINCT potency FROM ingredients;',h('The requested kind is potency.', 'Do not add columns that change the distinct combinations.'),{requires:'DISTINCT'})],['paired-rune','Paired Rune','spell','Remember labels that come in different strengths.',q('Return each different name-and-potency combination once.','SELECT DISTINCT name, potency FROM ingredients;',h('Select both requested facts.', 'DISTINCT operates on the whole output row.'),{requires:'DISTINCT'})],['quiet-catalog','Quiet Catalog','potion','Condense the non-glowing label list.',q('Return distinct names of non-glowing ingredients in ascending alphabetical order.','SELECT DISTINCT name FROM ingredients WHERE glowing = 0 ORDER BY name ASC;',h('Filter on glowing = 0.', 'Sort the deduplicated names explicitly.'),{requires:'DISTINCT',ordered:true})]],
});
