import { chapter, task as q, tutorial as t, page as p } from './content.js';
const h = (concept, step) => [concept, step];
export default chapter({id:'either-or',title:'Two ways to carry light',place:'The Herbarium',scene:'herbarium',topic:'OR · NOT · parentheses',brief:'Combine alternatives without changing their meaning.',tables:['ingredients'],
 storyPages:[p('The cracked lantern', 'IONA','A ferry lantern cracks on the bench. Iona can mend it with a glowing ingredient or a powerful dark one. “There can be more than one way to help. Write down exactly which ways count.”'),p('A careful exception','PROFESSOR QUILL','Quill points to a jar reserved for another crew. “Alternatives still need boundaries. A pair of parentheses can keep an exception from swallowing the whole request.”')],
 ending:p('A choice the crew can trust','IONA','The repair list keeps its alternatives and its exceptions intact. Iona tucks it into the lantern case. Nobody on the far shore will have to guess what you meant.'),
 tutorial:t(['OR keeps a row when either condition is true. NOT reverses a condition. The <> operator means not equal.', 'AND is evaluated before OR. Parentheses group the alternatives that should be considered together: (a OR b) AND c.', "Text values use single quotes: name = 'Crystal'. Double a single quote inside a value, as in 'Keeper''s lamp'. Table and column names are not text values."], "SELECT name FROM ingredients WHERE glowing = 0 OR potency < 6;",'Either non-glowing ingredients or ingredients below six qualify; a row satisfying both still appears only once.'),
 tasks:[q('Return name and potency where glowing is 1 OR potency is at least 7.', 'SELECT name, potency FROM ingredients WHERE glowing = 1 OR potency >= 7;',h('Either condition is enough.', 'Connect the two conditions with OR.'),{requires:'OR'}),q("Return id and name for ingredients that are NOT glowing (glowing = 1), excluding the name 'Mushroom'.", "SELECT id, name FROM ingredients WHERE NOT (glowing = 1) AND name <> 'Mushroom';",h('Use NOT around the glow comparison.', 'Combine it with a not-equal name condition.'),{requires:'NOT'}),q("Return name for ingredients that either glow or have potency at least 7, but exclude every ingredient named 'Crystal'. Group the alternatives with parentheses.", "SELECT name FROM ingredients WHERE (glowing = 1 OR potency >= 7) AND name <> 'Crystal';",h('The exclusion must apply to both alternatives.', 'Parentheses keep the OR conditions together.'),{requires:['OR','AND']})],
 crafts:[['forked-wisp','Forked Wisp','spell','Give a wisp two ways to find its charge.',q('Return id for ingredients with potency below 5 OR above 8.','SELECT id FROM ingredients WHERE potency < 5 OR potency > 8;',h('Both boundaries are excluded.', 'Use OR for the two separate ranges.'))],['quiet-oil','Quiet Oil','potion','Brew from everything outside the bright strong set.',q('Return name where it is NOT true that glowing is 1 AND potency is at least 7.','SELECT name FROM ingredients WHERE NOT (glowing = 1 AND potency >= 7);',h('Negate the whole pair of conditions.', 'Put the AND expression inside parentheses.'),{requires:'NOT'})],['choice-knot','Choice Knot','charm','Keep a spare route through the herbarium.',q("Return name and glowing where the name is 'Moonstone' OR the name is 'Emberroot'.","SELECT name, glowing FROM ingredients WHERE name = 'Moonstone' OR name = 'Emberroot';",h('Compare name separately for each alternative.', 'Single quotes mark text values.'))]],
});
