import { chapter, task as q, tutorial as t, page as p } from './content.js';
const h = (concept, step) => [concept, step];
export default chapter({id:'grouped-orders',title:'A bundle for each landing',place:'The Workshop',scene:'workshop',topic:'GROUP BY · multiple keys',brief:'Summarize records separately for each group.',tables:['orders'],
 storyPages:[p('Not one large crate','IONA','The totals fit on a slip of paper, but the ferry serves several landings. Iona unfolds a map. “A total tells us how much. A group tells us where it belongs.”'),p("A recipe within a route","PROFESSOR QUILL","Quill puts two differently colored flasks in a landing’s crate, then pauses. “We need the recipe on this list as well. A destination can request more than one kind of potion.” He adds a second heading.")],
 ending:p('The bundles take shape','IONA','Each landing has its own count and each recipe its own bundle. The workshop’s work now follows the route across the lake.'),
 tutorial:t(['GROUP BY divides source rows into groups and computes each aggregate separately inside each group.', 'Select the group keys plus aggregates. In SQLite, a bare selected column outside GROUP BY can come from an arbitrary row; avoid that ambiguous output.', 'GROUP BY destination, recipe_id creates a group for each combination. It does not group each column independently. GROUP BY does not guarantee output order.', "WHERE ordered_on >= '2026-09-01' AND ordered_on < '2026-10-01' selects September from fixed-width ISO dates. The start is included and the next month’s start is excluded; apply this row filter before GROUP BY."], 'SELECT recipe_id, SUM(batches) FROM orders GROUP BY recipe_id;', 'One row per recipe reports the batches requested across its orders.'),
 tasks:[q('Return destination and COUNT(*) per destination.','SELECT destination, COUNT(*) FROM orders GROUP BY destination;',h('The destination is the grouping key.', 'COUNT runs separately for each destination.'),{requires:['GROUP','BY']}),q('Return destination, recipe_id, and SUM(batches) for each destination-and-recipe combination.','SELECT destination, recipe_id, SUM(batches) FROM orders GROUP BY destination, recipe_id;',h('Group by both non-aggregated columns.', 'A combination gets one output row.'),{requires:['GROUP','BY']}),q('For undelivered orders, return recipe_id, COUNT(*), and SUM(batches), grouped by recipe_id and sorted by recipe_id ascending.','SELECT recipe_id, COUNT(*), SUM(batches) FROM orders WHERE delivered_on IS NULL GROUP BY recipe_id ORDER BY recipe_id ASC;',h('WHERE chooses rows before grouping.', 'ORDER BY makes the group display predictable.'),{requires:['GROUP','BY'],ordered:true})],
 crafts:[['landing-flask','Landing Flask','potion','Average the size of requests from each landing.',q('Return destination and AVG(batches) per destination.','SELECT destination, AVG(batches) FROM orders GROUP BY destination;',h('A separate average is needed for each landing.', 'Group on destination.'))],['recipe-seal','Recipe Seal','charm','Summarize completed work recipe by recipe.',q('Return recipe_id and COUNT(*) for delivered orders grouped by recipe_id.','SELECT recipe_id, COUNT(*) FROM orders WHERE delivered_on IS NOT NULL GROUP BY recipe_id;',h('Keep only known delivery dates first.', 'Then count within each recipe.'))],['daily-spark','Daily Spark','spell','Gather the September schedule for each landing.',q('For orders placed in September 2026, return ordered_on, destination, and SUM(batches) per date-and-destination combination. Use an inclusive September 1 boundary and exclusive October 1 boundary.',"SELECT ordered_on, destination, SUM(batches) FROM orders WHERE ordered_on >= '2026-09-01' AND ordered_on < '2026-10-01' GROUP BY ordered_on, destination;",h('Filter the ISO date strings with >= for the first day and < for the next month’s first day.', 'Then group by both ordered_on and destination.'))]],
});
