import { chapter, task as q, tutorial as t, page as p } from './content.js';
const h = (concept, step) => [concept, step];
export default chapter({id:'measured-brews',title:'Measures for the crossing',place:'The Workshop',scene:'workshop',topic:'Arithmetic · CAST · ROUND',brief:'Calculate values without losing fractions.',tables:['ingredients'],
 storyPages:[p('Half a measure','IONA','Iona splits a training brew into two flasks. One reading is odd. “A whole-number answer can hide half a measure. Tell the records when you need fractions.”'),p("A mark between the marks","PROFESSOR QUILL","Quill peers at the measuring glass. “The old dispatch sheet rounded too early. We copied that mistake for three crossings.” Iona adds a finer scale and keeps the unrounded readings beside it.")],
 ending:p('A fraction accounted for','IONA','Every flask receives its calculated measure. Iona circles the fractional readings in her notebook; small quantities still count.'),
 tutorial:t(['SELECT can calculate with +, -, *, and /. Parentheses group calculations before multiplication and division.', 'SQLite divides two integers using integer division: 5 / 2 is 2. Use a real value such as 2.0 or CAST(potency AS REAL) to preserve fractions.', 'ROUND(value, digits) rounds a numeric result. Division by zero returns NULL in SQLite; it is not a valid measured amount. NULLIF(denominator, 0) can make that missing denominator explicit.'], 'SELECT name, ROUND(potency / 3.0, 2) AS third_measure FROM ingredients;', 'A real denominator preserves thirds before rounding to two decimal places.'),
 tasks:[q('Return name and potency divided by 2.0 for every ingredient, preserving halves.','SELECT name, potency / 2.0 FROM ingredients;',h('A real operand requests real division.', 'Use 2.0, not integer 2.')),q('Return id and potency increased by 2 then multiplied by 3 for every ingredient.','SELECT id, (potency + 2) * 3 FROM ingredients;',h('The increase happens before multiplication.', 'Use parentheses around potency + 2.')),q('Return name and potency divided by 4, rounded to one decimal place. Use CAST to convert potency to REAL before dividing.','SELECT name, ROUND(CAST(potency AS REAL) / 4, 1) FROM ingredients;',h('CAST changes the numeric type before division.', 'ROUND wraps the calculated quotient.'),{requires:['CAST','ROUND']})],
 crafts:[['quarter-draught','Quarter Draught','potion','Divide each charge into four equal portions.',q('Return id and potency divided by 4.0 for every ingredient.','SELECT id, potency / 4.0 FROM ingredients;',h('Fractions should remain.', 'Use a real denominator.'))],['reserve-rune','Reserve Rune','spell','Calculate the reserve after a doubled charge.',q('Return name and twice the potency minus 1 for all ingredients.','SELECT name, potency * 2 - 1 FROM ingredients;',h('Multiply the potency first.', 'Subtract one from that result.'))],['ratio-vial','Ratio Vial','potion','Record an undefined self-ratio honestly for zero strength.',q('Return name and 10.0 divided by potency for every ingredient. Use NULLIF(potency, 0) as the denominator, leaving zero-strength ratios NULL.','SELECT name, 10.0 / NULLIF(potency, 0) FROM ingredients;',h('NULLIF returns NULL when its two arguments match.', 'Do not replace the missing ratio with zero.'),{requires:'NULLIF'})]],
});
