import { chapter, task as q, tutorial as t, page as p } from './content.js';
const h = (concept, step) => [concept, step];
export default chapter({id: 'named-columns', title: 'Labels for the lantern fleet', place: 'The Archive', scene: 'archive', topic: 'AS · comments', brief: 'Give returned columns useful names.', tables: ['ingredients'],
 storyPages: [p('A second shore', 'PROFESSOR QUILL', 'The ferry returns with a request: every landing needs a lantern before the next moonrise. Quill spreads blank dispatch sheets across his desk. “Our records need to make sense to someone who has never opened our catalog.”'), p('A note in the margin', 'IONA', 'Iona labels a crate, then adds a pencil note explaining her measurements. “Name the output clearly. Leave the next reader a reason, too.”')],
 ending: p('A readable manifest', 'PROFESSOR QUILL', 'The dispatch headings now say what the crew needs to know. Quill leaves room for notes beneath them. The academy is learning to share its knowledge beyond its walls.'),
 tutorial: t(['AS gives a result column a new heading; it does not rename the stored column. Write name AS ingredient to label a returned name.', 'A table alias such as ingredients AS i shortens later references to i.name. Column aliases and table aliases name different things.', 'A -- comment lasts to the end of its line. A /* comment */ can span lines. Comments explain your reasoning and are ignored by SQLite.'], 'SELECT id AS catalog_number FROM ingredients;', 'The stored id column is returned under the heading catalog_number.'),
 tasks: [q('Return name AS ingredient and potency AS strength for every ingredient, in that order.', 'SELECT name AS ingredient, potency AS strength FROM ingredients;', h('AS follows the original column or expression.', 'Give name the heading ingredient and potency the heading strength.'), {expectedColumns:['ingredient','strength']}), q('Return id AS jar_number and name AS jar_label for every ingredient.', 'SELECT id AS jar_number, name AS jar_label FROM ingredients;', h('A result heading can describe its purpose.', 'Put each alias immediately after its column.'), {expectedColumns:['jar_number','jar_label']}), q('For glowing ingredients, return name AS lantern_material and potency AS light_strength, in that order.', 'SELECT name AS lantern_material, potency AS light_strength FROM ingredients WHERE glowing = 1;', h('Headings affect presentation; WHERE still chooses the rows.', 'Read the original glowing column when filtering.'), {expectedColumns:['lantern_material','light_strength']})],
 crafts: [['label-ink','Manifest Ink','potion','Make ink for clear shipping labels.',q('Return name AS label for every non-glowing ingredient.', 'SELECT name AS label FROM ingredients WHERE glowing = 0;',h('Filter on glowing.', 'Alias the displayed name.'),{expectedColumns:['label']})],['number-seal','Number Seal','charm','Bind each label to a stable catalog number.',q('Return id AS seal_id and potency AS charge for all ingredients.', 'SELECT id AS seal_id, potency AS charge FROM ingredients;',h('Choose two columns.', 'Name their returned headings with AS.'),{expectedColumns:['seal_id','charge']})],['margin-light','Margin Light','spell','Illuminate the strongest entries on the dispatch sheet.',q('Return name AS material for ingredients with potency at least 7.', 'SELECT name AS material FROM ingredients WHERE potency >= 7;',h('At least includes seven.', 'The output has one renamed column.'),{expectedColumns:['material']})]],
});
