import { chapter, task as q, tutorial as t, page as p } from './content.js';
const h = (concept, step) => [concept, step];
export default chapter({id:'ordered-shelves',title:'First onto the ferry',place:'The Workshop',scene:'workshop',topic:'ORDER BY · LIMIT',brief:'Choose a stable order and a bounded result.',tables:['ingredients'],ordered:true,
 storyPages:[p('Only two places','IONA','The next ferry has room for two sample jars. Iona wants the strongest first, with a clear rule when strengths tie. “If two people read this list, they should pack the same crate.”'),p("Two equally strong jars","PROFESSOR QUILL","Quill sets two practice jars side by side. Their strengths match. “Give the tie a rule of its own,” he says. “The smallest catalog number will do. A clear rule saves a conversation at the dock.”")],
 ending:p('A place for every jar','IONA','The packing order is repeatable, even when two jars share a strength. The ferry crew loads the first crate without another question.'),
 tutorial:t(['Without ORDER BY, SQL does not promise a row order. ASC sorts ascending and is the default; DESC sorts descending.', 'Multiple sort keys apply from left to right. A unique ID as the final key resolves any remaining ties.', 'LIMIT n keeps the first n rows after sorting. Without a complete ordering, a top-n request may choose different tied rows.'], 'SELECT name, potency FROM ingredients ORDER BY potency ASC, id ASC LIMIT 2;', 'The two lowest strengths appear first, with smaller IDs resolving ties.'),
 tasks:[q('Return name and potency for all ingredients, strongest first; break strength ties by id ascending.','SELECT name, potency FROM ingredients ORDER BY potency DESC, id ASC;',h('Use DESC for strongest first.', 'Add id ASC after a comma.'),{ordered:true}),q('Return id and name for the first three labels alphabetically; break equal-name ties by id ascending.','SELECT id, name FROM ingredients ORDER BY name ASC, id ASC LIMIT 3;',h('Sort before limiting.', 'An ID makes equal names deterministic.'),{ordered:true}),q('Return name and potency for the two strongest glowing ingredients; break potency ties by id ascending.','SELECT name, potency FROM ingredients WHERE glowing = 1 ORDER BY potency DESC, id ASC LIMIT 2;',h('Filter to glowing rows first.', 'Order by strength and then identity before taking two.'),{ordered:true})],
 crafts:[['gentle-drops','Gentle Drops','potion','Pack the gentlest single sample.',q('Return id and name for the weakest ingredient, breaking ties by id ascending.','SELECT id, name FROM ingredients ORDER BY potency ASC, id ASC LIMIT 1;',h('Weakest sorts ascending.', 'Use a stable second key before LIMIT 1.'),{ordered:true})],['reverse-index','Reverse Index','spell','Read the labels from the far end of the shelf.',q('Return name for all ingredients in descending alphabetical order, breaking ties by id ascending.','SELECT name FROM ingredients ORDER BY name DESC, id ASC;',h('Descending reverses the alphabet.', 'Keep id ascending for equal labels.'),{ordered:true})],['dark-cargo','Dark Cargo','charm','Reserve two quiet jars for the night boat.',q('Return id, name, and potency for up to two non-glowing ingredients, strongest first, with id ascending for ties.','SELECT id, name, potency FROM ingredients WHERE glowing = 0 ORDER BY potency DESC, id ASC LIMIT 2;',h('Filter before ordering.', 'LIMIT may return fewer rows when fewer qualify.'),{ordered:true})]],
});
