import { chapter, task as q, tutorial as t, page as p } from './content.js';
const h = (concept, step) => [concept, step];
const stock = 'FROM ingredients AS i LEFT JOIN stock AS s ON i.id = s.ingredient_id';
export default chapter({id:'unknown-values',title:'The honest blank',place:'The Workshop',scene:'workshop',topic:'IS NULL · COALESCE',brief:'Keep missing records distinct from zero.',tables:['ingredients','stock'],
 storyPages:[p('A count interrupted','PROFESSOR QUILL','Quill returns with the stock book. Rain blurred part of his count. “Some shelves are empty. Some I still cannot account for. Please keep those statements separate.”'),p('A display is not a count','IONA','Iona draws a dash in a spare display column. “We can choose what a blank looks like without pretending we measured it.”')],
 ending:p('Room for what is unknown','PROFESSOR QUILL','The uncounted shelves remain visible. Quill takes a fresh sheet and a lantern; this time he knows which measurements are still missing.'),
 tutorial:t(['NULL represents missing or unknown information. A LEFT JOIN supplies NULL on the right when no row matches. Zero is a known number; it is not NULL.', 'Use IS NULL or IS NOT NULL to test missingness. Comparisons such as = NULL do not become true, so they do not select missing records.', 'COALESCE returns the first non-NULL argument. COALESCE(s.quantity, -1) can display a sentinel for unknown stock. The sentinel is an output convention, not an observed quantity.'],`SELECT i.name, COALESCE(s.quantity, -1) AS display_quantity ${stock};`,'Every ingredient remains; missing quantities display -1 while recorded zero remains zero.'),
 tasks:[q('Return ingredient name for every ingredient with no matching stock record. Use LEFT JOIN and IS NULL.',`SELECT i.name ${stock} WHERE s.ingredient_id IS NULL;`,h('Keep ingredients on the left.', 'Test the right-hand key for NULL.'),{requires:['LEFT','JOIN','NULL']}),q('Return ingredient name and quantity only where a stock quantity is recorded, including zero.',`SELECT i.name, s.quantity ${stock} WHERE s.quantity IS NOT NULL;`,h('Recorded zero passes IS NOT NULL.', 'Filter the quantity after the LEFT JOIN.')),q('Return every ingredient name and its quantity, displaying -1 for unknown quantity using COALESCE. Do not replace recorded zero.',`SELECT i.name, COALESCE(s.quantity, -1) ${stock};`,h('Keep every ingredient using a LEFT JOIN.', 'COALESCE replaces only NULL.'),{requires:'COALESCE'})],
 crafts:[['blank-signal','Blank Signal','spell','Mark jars awaiting a real count.',q('Return ingredient id and name only for missing stock records.',`SELECT i.id, i.name ${stock} WHERE s.ingredient_id IS NULL;`,h('A missing right-hand key identifies an unmatched row.', 'Return the ID from ingredients.'))],['counted-seal','Counted Seal','charm','Seal known empty shelves for replenishment.',q('Return ingredient name and quantity for recorded quantities equal to zero.',`SELECT i.name, s.quantity ${stock} WHERE s.quantity = 0;`,h('A zero comparison excludes NULL.', 'Keep the recorded zero rather than substituting it.'))],['ledger-tonic','Ledger Tonic','potion','Make the practice display explicit about unknowns.',q('Return ingredient id and quantity for all ingredients, displaying -99 for unknown quantities.',`SELECT i.id, COALESCE(s.quantity, -99) ${stock};`,h('Preserve all left-hand rows.', 'Use -99 as COALESCE’s second argument.'))]],
});
